import type { Metadata } from "next";
import { Bowlby_One_SC, Architects_Daughter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Infobar from "../components/Infobar";
import { arch } from "os";

const bowlbyOneSC = Bowlby_One_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bowlbyOneSC",
});

const architectsDaughter = Architects_Daughter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-architectsDaughter",
});


export const metadata: Metadata = {
  title: "Rettungsanker-Freiburg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bowlbyOneSC.variable} ${architectsDaughter.variable}`}>
      <body className={`${architectsDaughter.className} antialiased`}>
<Navbar />
<Infobar />
<main className="w-screen min-h-screen flex flex-col items-center justify-between bg-amber-100">{children}</main>
        </body>
    </html>
  );
}