import type { Metadata } from "next";
import { Bowlby_One_SC } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Infobar from "../components/Infobar";
import Footer from "../components/Footer";

const bowlbyOneSC = Bowlby_One_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bowlbyOneSC",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bowlbyOneSC.variable}>
      <body className={`${bowlbyOneSC.className} antialiased`}>
        <Navbar />
        <Infobar />
        {children}
      </body>
    </html>
  );
}
