import type { Metadata } from "next";
import { Bowlby_One_SC, Architects_Daughter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navbar";
import InfoBar from"../components/Infobar";


const bowlbyOneSC = Bowlby_One_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bowlbyOneSC",
});

const architectsDaughter = Architects_Daughter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-architectsDaughter",
});


export const metadata: Metadata = {
  title: "Rettungsanker-Freiburg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bowlbyOneSC.variable} ${architectsDaughter.variable}`}>
      <body className={`${architectsDaughter.className} antialiased`}>
        <Navigation/>
        <InfoBar/>

<main className=" bg-stone-800 flex flex-col items-center justify-between">{children}</main>
        </body>
    </html>
  );
}